title: RudeRaph
description: Cybersecurity portfolio — HTB writeups, tools, and certifications
author: RudeRaph

# Update these with your real links
github_username: RudeRaph

markdown: kramdown
theme: minima

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

defaults:
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
